name: CKDX9Rasterizer

on:
  push:
    branches: [ master ]
    paths:
      - 'CKDX9Rasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'CKDX9Rasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_ARGS: -DVIRTOOLS_SDK_FETCH_FROM_GIT=ON -DUSE_D3D9EX=OFF -DTRACY_ENABLE=OFF -A Win32

jobs:
  build-dx9:
    runs-on: windows-latest
    env:
      PROJECT_ROOT: ${{github.workspace}}
      VENDOR_ROOT: ${{github.workspace}}/vendor
      PROJECT_NAME: CKDX9Rasterizer
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x86

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -B ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build -S ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_ARGS}}

      - name: Build
        working-directory: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build
        run: cmake --build ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{env.PROJECT_ROOT}}
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Release Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{env.PROJECT_NAME}}
          path: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build/${{env.BUILD_TYPE}}
