name: CKGLRasterizer

on:
  push:
    branches: [ master ]
    paths:
      - 'CKGLRasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'CKGLRasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_ARGS: -DVIRTOOLS_SDK_FETCH_FROM_GIT=ON -DTRACY_ENABLE=OFF -A Win32

jobs:
  build-gl:
    runs-on: windows-latest
    env:
      PROJECT_ROOT: ${{github.workspace}}
      VENDOR_ROOT: ${{github.workspace}}/vendor
      PROJECT_NAME: CKGLRasterizer
      GLEW_VERSION: "2.2.0"
    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Fetch git submodules
        run: git submodule update --init --recursive --remote

      - name: Download GLEW
        if:   steps.cache.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1.3.0
        id: download-glew  # Remember to give an ID if you need the output filename
        with:
          url: "https://github.com/nigels-com/glew/releases/download/glew-${{env.GLEW_VERSION}}/glew-${{env.GLEW_VERSION}}-win32.zip"
          target: ${{env.VENDOR_ROOT}}
          filename: glew.zip

      - name: Extract and setup GLEW
        if:   steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{env.VENDOR_ROOT}}
        run: (7z x ${{env.VENDOR_ROOT}}/glew.zip -o${{env.VENDOR_ROOT}}) -and (ren glew-${{env.GLEW_VERSION}} glew)

      # Setup MSVC command prompt environment vars
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build -S ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_ARGS}}

      - name: Build
        working-directory: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build
        run: cmake --build ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{env.PROJECT_ROOT}}
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PROJECT_NAME}}
          path: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build/${{env.BUILD_TYPE}}
