name: CKVkRasterizer

on:
  push:
    branches: [ master ]
    paths:
      - 'CKVkRasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'CKVkRasterizer/**'
      - '.github/**'
      - 'buildsystems/**'
      - 'vendor/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_ARGS: -DVIRTOOLS_SDK_FETCH_FROM_GIT=ON -DTRACY_ENABLE=OFF -A Win32
  VULKAN_SDK: C:\VulkanSDK\

jobs:
  build-vk:
    runs-on: windows-latest
    env:
      PROJECT_ROOT: ${{github.workspace}}
      VENDOR_ROOT: ${{github.workspace}}/vendor
      PROJECT_NAME: CKVkRasterizer
    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Fetch git submodules
        run: git submodule update --init --recursive --remote
        
      # Setup MSVC command prompt environment vars
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache Vulkan SDK
        id: cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: "C:\\VulkanSDK\\1.3.261.0"
          key: vulkan-sdk-1.3.261.0

      - name: Setup Vulkan
        run: |
            $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
            echo Version $ver
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
            echo Downloaded
            .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.32bit com.lunarg.vulkan.sdl2 com.lunarg.vulkan.glm com.lunarg.vulkan.volk com.lunarg.vulkan.vma com.lunarg.vulkan.debug com.lunarg.vulkan.debug32

      - name: Configure CMake
        run: cmake -B ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build -S ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_ARGS}}

      - name: Build
        working-directory: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build
        run: cmake --build ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{env.PROJECT_ROOT}}
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PROJECT_NAME}}
          path: ${{env.PROJECT_ROOT}}/${{env.PROJECT_NAME}}/build/${{env.BUILD_TYPE}}
